# Allwinner A733 quad core 2GB/4GB RAM
BOARD_NAME="Orange Pi Zero 4"
BOARDFAMILY="sun60iw2"
BOOTCONFIG="sun60iw2p1_t736_defconfig"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="allwinner/sun60i-a733-orangepi-zero4.dtb"
MODULES="aic8800_fdrv aic8800_btlpm"
KERNEL_TARGET="current legacy"
DISTRIB_TYPE_CURRENT="bookworm jammy bullseye resolute trixie"
DISTRIB_TYPE_LEGACY="bookworm jammy bullseye"
SKIP_BOOTSPLASH="yes" # Skip boot splash patch, conflicts with CONFIG_VT=yes
REVISION="1.0.0"
