# Rockchip RK3588s SoC
BOARD_NAME="Orange Pi CM5 Tablet"
BOARDFAMILY="rockchip-rk3588"
BOOTCONFIG="orangepi_cm5_tablet_defconfig"
KERNEL_TARGET="legacy,current,next"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3588s-orangepi-cm5-tablet.dtb"
BOOT_SCENARIO="spl-blobs"
BOOT_SUPPORT_SPI="yes"
SKIP_BOOTSPLASH="yes" # Skip boot splash patch, conflicts with CONFIG_VT=yes
DISTRIB_TYPE_LEGACY="bullseye bookworm focal jammy"
DISTRIB_TYPE_NEXT="resolute trixie"
MODULES_BLACKLIST_NEXT="bcmdhd"
REVISION="1.0.2"
