# Rockchip RK3588 SoC
BOARD_NAME="Orange Pi 5 Plus"
BOARDFAMILY="rockchip-rk3588"
BOOTCONFIG="orangepi_5_plus_defconfig"
KERNEL_TARGET="legacy,current,next"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3588-orangepi-5-plus.dtb"
BOOT_SCENARIO="spl-blobs"
BOOT_SUPPORT_SPI="yes"
SKIP_BOOTSPLASH="yes" # Skip boot splash patch, conflicts with CONFIG_VT=yes
DISTRIB_TYPE_LEGACY="bullseye bookworm bionic focal jammy"
DISTRIB_TYPE_CURRENT="bullseye bookworm focal jammy resolute trixie"
DISTRIB_TYPE_NEXT="resolute trixie"
MODULES_BLACKLIST_NEXT="bcmdhd"
REVISION="1.2.2"
