# Allwinner A733 quad core 2GB/4GB/8GB/16GB RAM
BOARD_NAME="Orange Pi 4 Pro"
BOARDFAMILY="sun60iw2"
BOOTCONFIG="sun60iw2p1_t736_defconfig"
BOOT_FDT_FILE="allwinner/sun60i-a733-orangepi-4-pro.dtb"
MODULES="aic8800_fdrv aic8800_btlpm"
KERNEL_TARGET="current"
DISTRIB_TYPE_CURRENT="bookworm jammy bullseye"
SKIP_BOOTSPLASH="yes" # Skip boot splash patch, conflicts with CONFIG_VT=yes
REVISION="1.0.4"
