# Cix P1 SoC
BOARD_NAME="Orange Pi 6 Plus"
BOARDFAMILY="cix"
KERNEL_TARGET="current"
IMAGE_PARTITION_TABLE="gpt"
DISTRIB_TYPE_CURRENT="bookworm"
MODULES_CURRENT="armcb_isp_v4l2 btusb"
PLYMOUTH="no"
BUILD_MINIMAL="no"
REVISION="1.0.0"
